name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"
    
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: dbt-labs/actions/.github/workflows/stale-bot-matrix.yml@main
